version: '3'
services:
  ssh-tunnel:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SSH_SERVER=bigtyre.com.au          # Replace with the actual hostname or IP of host1
      - SSH_USER=zabbix-agent
      - SSH_TUNNEL_PORT=10050
      - SSH_TUNNEL_HOST=127.0.0.1
    ports:
      - "10050:10000"
    secrets:
      - user_ssh_key
secrets:
  user_ssh_key:
    file: key